### ISSUE TITLE
Failed to translate properties

### ISSUE THREAD

**Issue by m-art-in** [Daniel-KM/Omeka-S-module-Internationalisation#1]
Many thanks for the helpful module. I use Omeka 2.1.2 and also installed the PHP extension _intl_. Switching between different pages works very well, but I can't manage to display only the respective attributes of a language at the item and item set level. 

The readme of the module says that it has to be changed in the file  application/src/Api/Representation/AbstractResourceEntityRepresentation.php (Patch #1506). with Omeka 2.1.2 this step is omitted (I guess). Nevertheless the attributes are not displayed according to their language. 

When I try to use the translation via the theme  with the code: 

```
$localeValue = $this->plugin('localeValue');
echo $localeValue($item, 'dcterms:title');

```
I get this error message:

`TypeError
Argument 2 passed to Internationalisation\View\Helper\LocaleValue::__construct() must be of the type array, null given, called in /.../modules/Internationalisation/src/Service/ViewHelper/LocaleValueFactory.php on line 33`

What can I do? Thanks for help

**Comment by Daniel-KM** [comment]
Yes, the patch 1506 is integrated upstream, so you don't need to integrate it anymore. So you don't have to use the `localeValue()` any more, except for the title. I fixed the issue above too in last version.

**Comment by Daniel-KM** [comment]
You can modify the settings in admin > settings too.

**Comment by m-art-in** [comment]
Thanks for the fix! Will it work somehow with Omeka's function $item->displayValues(), too?

**Comment by m-art-in** [comment]
> 
> 
> Thanks for the fix! Will it work somehow with Omeka's function $item->displayValues(), too?

I found the solution myself and changed some code in common/resource-values.phtml (which I copied first into my theme).
