### ISSUE TITLE
Call to undefined method Omeka\Api\Representation\ModuleRepresentation::getIni()

### ISSUE THREAD

**Issue by nathanxmeyer** [Daniel-KM/Omeka-S-module-Internationalisation#6]
Hello, I have Omeka-S v4.0.1 PHP v8.1 and Apache v2.4.  I get this error when installing internationalization:

Error
Call to undefined method Omeka\Api\Representation\ModuleRepresentation::getIni()

Details:

Error: Call to undefined method Omeka\Api\Representation\ModuleRepresentation::getIni() in /var/www/eudia/modules/EasyAdmin/src/Controller/AddonsController.php:190
Stack trace:
#0 /var/www/eudia/modules/EasyAdmin/src/Controller/AddonsController.php(61): EasyAdmin\Controller\AddonsController->installAddon()
#1 /var/www/eudia/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): EasyAdmin\Controller\AddonsController->indexAction()
#2 /var/www/eudia/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#3 /var/www/eudia/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#4 /var/www/eudia/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil()
#5 /var/www/eudia/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch()
#6 /var/www/eudia/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch()
#7 /var/www/eudia/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#8 /var/www/eudia/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil()
#9 /var/www/eudia/index.php(21): Laminas\Mvc\Application->run()
#10 {main}

**Comment by Daniel-KM** [comment]
Fixed in 3.4.11.
