### ISSUE TITLE
Conflict with BlockPlus module

### ISSUE THREAD

**Issue by akprtll** [Daniel-KM/Omeka-S-module-Internationalisation#8]
Running Omeka S 4.1.1; when [BlockPlus](https://github.com/Daniel-KM/Omeka-S-module-BlockPlus/) (using version 3.4.26) is active, the "Translations / Select translations of this page" interface does not appear when editing pages. Turning off BlockPlus makes the interface reappear.

**Comment by m8hu** [comment]
Echoing the error above, I'm seeing the same issue. 

I can confirm I have translations and blockplus running on the previous version of Omeka S successfully.

**Comment by Daniel-KM** [comment]
Thanks, this is fixed in version 3.4.14.

**Comment by Daniel-KM** [comment]
Use Block Plus version 3.4.29 too.
